### ISSUE TITLE
FAQ panel(s) stuck @ 2/3 working

### ISSUE THREAD

**Issue by andrewbates09** [WSU-LUG/wsucon#3]
Can interact beyond: "Do I have to stay the whole 24 hours?" on faq.

**Comment by andrewbates09** [comment]
Per our previous conversation, to live test: publish to a branch called "betacon" and it will run up live on the betacon website. Merging into the master will update the wsucon website.

**Comment by RachelMiri** [comment]
ka-bam, faq fixed

**Comment by RachelMiri** [comment]
ka-bam, faq fixed
